// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: userOrgAssociation/userOrgAssociation.proto

package userOrgAssociation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrgAssociationEnum_Role int32

const (
	UserOrgAssociationEnum_Owner UserOrgAssociationEnum_Role = 0
	UserOrgAssociationEnum_Admin UserOrgAssociationEnum_Role = 1
	UserOrgAssociationEnum_User  UserOrgAssociationEnum_Role = 2
)

// Enum value maps for UserOrgAssociationEnum_Role.
var (
	UserOrgAssociationEnum_Role_name = map[int32]string{
		0: "Owner",
		1: "Admin",
		2: "User",
	}
	UserOrgAssociationEnum_Role_value = map[string]int32{
		"Owner": 0,
		"Admin": 1,
		"User":  2,
	}
)

func (x UserOrgAssociationEnum_Role) Enum() *UserOrgAssociationEnum_Role {
	p := new(UserOrgAssociationEnum_Role)
	*p = x
	return p
}

func (x UserOrgAssociationEnum_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOrgAssociationEnum_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_userOrgAssociation_userOrgAssociation_proto_enumTypes[0].Descriptor()
}

func (UserOrgAssociationEnum_Role) Type() protoreflect.EnumType {
	return &file_userOrgAssociation_userOrgAssociation_proto_enumTypes[0]
}

func (x UserOrgAssociationEnum_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserOrgAssociationEnum_Role) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserOrgAssociationEnum_Role(num)
	return nil
}

// Deprecated: Use UserOrgAssociationEnum_Role.Descriptor instead.
func (UserOrgAssociationEnum_Role) EnumDescriptor() ([]byte, []int) {
	return file_userOrgAssociation_userOrgAssociation_proto_rawDescGZIP(), []int{0, 0}
}

type UserOrgAssociationEnum_Status int32

const (
	UserOrgAssociationEnum_Active   UserOrgAssociationEnum_Status = 0
	UserOrgAssociationEnum_Inactive UserOrgAssociationEnum_Status = 1
	UserOrgAssociationEnum_Deleted  UserOrgAssociationEnum_Status = 2
)

// Enum value maps for UserOrgAssociationEnum_Status.
var (
	UserOrgAssociationEnum_Status_name = map[int32]string{
		0: "Active",
		1: "Inactive",
		2: "Deleted",
	}
	UserOrgAssociationEnum_Status_value = map[string]int32{
		"Active":   0,
		"Inactive": 1,
		"Deleted":  2,
	}
)

func (x UserOrgAssociationEnum_Status) Enum() *UserOrgAssociationEnum_Status {
	p := new(UserOrgAssociationEnum_Status)
	*p = x
	return p
}

func (x UserOrgAssociationEnum_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOrgAssociationEnum_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_userOrgAssociation_userOrgAssociation_proto_enumTypes[1].Descriptor()
}

func (UserOrgAssociationEnum_Status) Type() protoreflect.EnumType {
	return &file_userOrgAssociation_userOrgAssociation_proto_enumTypes[1]
}

func (x UserOrgAssociationEnum_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserOrgAssociationEnum_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserOrgAssociationEnum_Status(num)
	return nil
}

// Deprecated: Use UserOrgAssociationEnum_Status.Descriptor instead.
func (UserOrgAssociationEnum_Status) EnumDescriptor() ([]byte, []int) {
	return file_userOrgAssociation_userOrgAssociation_proto_rawDescGZIP(), []int{0, 1}
}

type UserOrgAssociationEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserOrgAssociationEnum) Reset() {
	*x = UserOrgAssociationEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userOrgAssociation_userOrgAssociation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOrgAssociationEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrgAssociationEnum) ProtoMessage() {}

func (x *UserOrgAssociationEnum) ProtoReflect() protoreflect.Message {
	mi := &file_userOrgAssociation_userOrgAssociation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrgAssociationEnum.ProtoReflect.Descriptor instead.
func (*UserOrgAssociationEnum) Descriptor() ([]byte, []int) {
	return file_userOrgAssociation_userOrgAssociation_proto_rawDescGZIP(), []int{0}
}

type UserOrgAssociation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *string                        `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	UserId    *string                        `protobuf:"bytes,2,req,name=userId" json:"userId,omitempty"`
	OrgId     *string                        `protobuf:"bytes,3,req,name=orgId" json:"orgId,omitempty"`
	Role      *UserOrgAssociationEnum_Role   `protobuf:"varint,4,req,name=role,enum=UserOrgAssociationEnum_Role" json:"role,omitempty"`
	Status    *UserOrgAssociationEnum_Status `protobuf:"varint,5,req,name=status,enum=UserOrgAssociationEnum_Status" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp         `protobuf:"bytes,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt *timestamppb.Timestamp         `protobuf:"bytes,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt *timestamppb.Timestamp         `protobuf:"bytes,8,opt,name=deletedAt" json:"deletedAt,omitempty"`
}

func (x *UserOrgAssociation) Reset() {
	*x = UserOrgAssociation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userOrgAssociation_userOrgAssociation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOrgAssociation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrgAssociation) ProtoMessage() {}

func (x *UserOrgAssociation) ProtoReflect() protoreflect.Message {
	mi := &file_userOrgAssociation_userOrgAssociation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrgAssociation.ProtoReflect.Descriptor instead.
func (*UserOrgAssociation) Descriptor() ([]byte, []int) {
	return file_userOrgAssociation_userOrgAssociation_proto_rawDescGZIP(), []int{1}
}

func (x *UserOrgAssociation) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UserOrgAssociation) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *UserOrgAssociation) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *UserOrgAssociation) GetRole() UserOrgAssociationEnum_Role {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return UserOrgAssociationEnum_Owner
}

func (x *UserOrgAssociation) GetStatus() UserOrgAssociationEnum_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserOrgAssociationEnum_Active
}

func (x *UserOrgAssociation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserOrgAssociation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserOrgAssociation) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_userOrgAssociation_userOrgAssociation_proto protoreflect.FileDescriptor

var file_userOrgAssociation_userOrgAssociation_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x41, 0x73, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71,
	0x0a, 0x16, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x26, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x02,
	0x22, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10,
	0x02, 0x22, 0xea, 0x02, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x41, 0x73,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x72, 0x67, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x75,
	0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x3e,
	0x5a, 0x3c, 0x65, 0x74, 0x6e, 0x61, 0x73, 0x79, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x4f, 0x72, 0x67, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
}

var (
	file_userOrgAssociation_userOrgAssociation_proto_rawDescOnce sync.Once
	file_userOrgAssociation_userOrgAssociation_proto_rawDescData = file_userOrgAssociation_userOrgAssociation_proto_rawDesc
)

func file_userOrgAssociation_userOrgAssociation_proto_rawDescGZIP() []byte {
	file_userOrgAssociation_userOrgAssociation_proto_rawDescOnce.Do(func() {
		file_userOrgAssociation_userOrgAssociation_proto_rawDescData = protoimpl.X.CompressGZIP(file_userOrgAssociation_userOrgAssociation_proto_rawDescData)
	})
	return file_userOrgAssociation_userOrgAssociation_proto_rawDescData
}

var file_userOrgAssociation_userOrgAssociation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_userOrgAssociation_userOrgAssociation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_userOrgAssociation_userOrgAssociation_proto_goTypes = []any{
	(UserOrgAssociationEnum_Role)(0),   // 0: UserOrgAssociationEnum.Role
	(UserOrgAssociationEnum_Status)(0), // 1: UserOrgAssociationEnum.Status
	(*UserOrgAssociationEnum)(nil),     // 2: UserOrgAssociationEnum
	(*UserOrgAssociation)(nil),         // 3: UserOrgAssociation
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_userOrgAssociation_userOrgAssociation_proto_depIdxs = []int32{
	0, // 0: UserOrgAssociation.role:type_name -> UserOrgAssociationEnum.Role
	1, // 1: UserOrgAssociation.status:type_name -> UserOrgAssociationEnum.Status
	4, // 2: UserOrgAssociation.createdAt:type_name -> google.protobuf.Timestamp
	4, // 3: UserOrgAssociation.updatedAt:type_name -> google.protobuf.Timestamp
	4, // 4: UserOrgAssociation.deletedAt:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_userOrgAssociation_userOrgAssociation_proto_init() }
func file_userOrgAssociation_userOrgAssociation_proto_init() {
	if File_userOrgAssociation_userOrgAssociation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userOrgAssociation_userOrgAssociation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserOrgAssociationEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userOrgAssociation_userOrgAssociation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserOrgAssociation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userOrgAssociation_userOrgAssociation_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userOrgAssociation_userOrgAssociation_proto_goTypes,
		DependencyIndexes: file_userOrgAssociation_userOrgAssociation_proto_depIdxs,
		EnumInfos:         file_userOrgAssociation_userOrgAssociation_proto_enumTypes,
		MessageInfos:      file_userOrgAssociation_userOrgAssociation_proto_msgTypes,
	}.Build()
	File_userOrgAssociation_userOrgAssociation_proto = out.File
	file_userOrgAssociation_userOrgAssociation_proto_rawDesc = nil
	file_userOrgAssociation_userOrgAssociation_proto_goTypes = nil
	file_userOrgAssociation_userOrgAssociation_proto_depIdxs = nil
}
