// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: invite/invite.proto

package invite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteEnum_Role int32

const (
	InviteEnum_Owner InviteEnum_Role = 0
	InviteEnum_Admin InviteEnum_Role = 1
	InviteEnum_User  InviteEnum_Role = 2
)

// Enum value maps for InviteEnum_Role.
var (
	InviteEnum_Role_name = map[int32]string{
		0: "Owner",
		1: "Admin",
		2: "User",
	}
	InviteEnum_Role_value = map[string]int32{
		"Owner": 0,
		"Admin": 1,
		"User":  2,
	}
)

func (x InviteEnum_Role) Enum() *InviteEnum_Role {
	p := new(InviteEnum_Role)
	*p = x
	return p
}

func (x InviteEnum_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteEnum_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_invite_invite_proto_enumTypes[0].Descriptor()
}

func (InviteEnum_Role) Type() protoreflect.EnumType {
	return &file_invite_invite_proto_enumTypes[0]
}

func (x InviteEnum_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InviteEnum_Role) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InviteEnum_Role(num)
	return nil
}

// Deprecated: Use InviteEnum_Role.Descriptor instead.
func (InviteEnum_Role) EnumDescriptor() ([]byte, []int) {
	return file_invite_invite_proto_rawDescGZIP(), []int{0, 0}
}

type InviteEnum_Status int32

const (
	InviteEnum_Active   InviteEnum_Status = 0
	InviteEnum_Accepted InviteEnum_Status = 1
	InviteEnum_Rejected InviteEnum_Status = 2
	InviteEnum_Expired  InviteEnum_Status = 3
	InviteEnum_Deleted  InviteEnum_Status = 4
)

// Enum value maps for InviteEnum_Status.
var (
	InviteEnum_Status_name = map[int32]string{
		0: "Active",
		1: "Accepted",
		2: "Rejected",
		3: "Expired",
		4: "Deleted",
	}
	InviteEnum_Status_value = map[string]int32{
		"Active":   0,
		"Accepted": 1,
		"Rejected": 2,
		"Expired":  3,
		"Deleted":  4,
	}
)

func (x InviteEnum_Status) Enum() *InviteEnum_Status {
	p := new(InviteEnum_Status)
	*p = x
	return p
}

func (x InviteEnum_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteEnum_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_invite_invite_proto_enumTypes[1].Descriptor()
}

func (InviteEnum_Status) Type() protoreflect.EnumType {
	return &file_invite_invite_proto_enumTypes[1]
}

func (x InviteEnum_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InviteEnum_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InviteEnum_Status(num)
	return nil
}

// Deprecated: Use InviteEnum_Status.Descriptor instead.
func (InviteEnum_Status) EnumDescriptor() ([]byte, []int) {
	return file_invite_invite_proto_rawDescGZIP(), []int{0, 1}
}

type InviteEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InviteEnum) Reset() {
	*x = InviteEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_invite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteEnum) ProtoMessage() {}

func (x *InviteEnum) ProtoReflect() protoreflect.Message {
	mi := &file_invite_invite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteEnum.ProtoReflect.Descriptor instead.
func (*InviteEnum) Descriptor() ([]byte, []int) {
	return file_invite_invite_proto_rawDescGZIP(), []int{0}
}

type Invite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *string                `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	InviteBy   *string                `protobuf:"bytes,2,req,name=inviteBy" json:"inviteBy,omitempty"`
	InviteFor  *string                `protobuf:"bytes,3,req,name=inviteFor" json:"inviteFor,omitempty"`
	OrgId      *string                `protobuf:"bytes,4,req,name=orgId" json:"orgId,omitempty"`
	Role       *InviteEnum_Role       `protobuf:"varint,5,req,name=role,enum=InviteEnum_Role" json:"role,omitempty"`
	Status     *InviteEnum_Status     `protobuf:"varint,6,req,name=status,enum=InviteEnum_Status" json:"status,omitempty"`
	InviteLink *string                `protobuf:"bytes,7,req,name=inviteLink" json:"inviteLink,omitempty"`
	ExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiresAt" json:"expiresAt,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deletedAt" json:"deletedAt,omitempty"`
}

func (x *Invite) Reset() {
	*x = Invite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_invite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_invite_invite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_invite_invite_proto_rawDescGZIP(), []int{1}
}

func (x *Invite) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Invite) GetInviteBy() string {
	if x != nil && x.InviteBy != nil {
		return *x.InviteBy
	}
	return ""
}

func (x *Invite) GetInviteFor() string {
	if x != nil && x.InviteFor != nil {
		return *x.InviteFor
	}
	return ""
}

func (x *Invite) GetOrgId() string {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return ""
}

func (x *Invite) GetRole() InviteEnum_Role {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return InviteEnum_Owner
}

func (x *Invite) GetStatus() InviteEnum_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return InviteEnum_Active
}

func (x *Invite) GetInviteLink() string {
	if x != nil && x.InviteLink != nil {
		return *x.InviteLink
	}
	return ""
}

func (x *Invite) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Invite) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invite) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Invite) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_invite_invite_proto protoreflect.FileDescriptor

var file_invite_invite_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x26, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x02, 0x22, 0x4a, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x04, 0x22, 0xc2, 0x03, 0x0a, 0x06, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x79,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x42, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x72, 0x67, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74,
	0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x2e,
	0x5a, 0x2c, 0x65, 0x74, 0x6e, 0x61, 0x73, 0x79, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
}

var (
	file_invite_invite_proto_rawDescOnce sync.Once
	file_invite_invite_proto_rawDescData = file_invite_invite_proto_rawDesc
)

func file_invite_invite_proto_rawDescGZIP() []byte {
	file_invite_invite_proto_rawDescOnce.Do(func() {
		file_invite_invite_proto_rawDescData = protoimpl.X.CompressGZIP(file_invite_invite_proto_rawDescData)
	})
	return file_invite_invite_proto_rawDescData
}

var file_invite_invite_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_invite_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_invite_invite_proto_goTypes = []any{
	(InviteEnum_Role)(0),          // 0: InviteEnum.Role
	(InviteEnum_Status)(0),        // 1: InviteEnum.Status
	(*InviteEnum)(nil),            // 2: InviteEnum
	(*Invite)(nil),                // 3: Invite
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_invite_invite_proto_depIdxs = []int32{
	0, // 0: Invite.role:type_name -> InviteEnum.Role
	1, // 1: Invite.status:type_name -> InviteEnum.Status
	4, // 2: Invite.expiresAt:type_name -> google.protobuf.Timestamp
	4, // 3: Invite.createdAt:type_name -> google.protobuf.Timestamp
	4, // 4: Invite.updatedAt:type_name -> google.protobuf.Timestamp
	4, // 5: Invite.deletedAt:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_invite_invite_proto_init() }
func file_invite_invite_proto_init() {
	if File_invite_invite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_invite_invite_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InviteEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_invite_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Invite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_invite_invite_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invite_invite_proto_goTypes,
		DependencyIndexes: file_invite_invite_proto_depIdxs,
		EnumInfos:         file_invite_invite_proto_enumTypes,
		MessageInfos:      file_invite_invite_proto_msgTypes,
	}.Build()
	File_invite_invite_proto = out.File
	file_invite_invite_proto_rawDesc = nil
	file_invite_invite_proto_goTypes = nil
	file_invite_invite_proto_depIdxs = nil
}
